#!/bin/bash

echo "" > zones/pro-db.orionet.re

for i in {1..255}
do
   echo "$i.member   IN	A	192.168.255.$i" >> zones/pro-db.orionet.re
   echo "$i         IN MX 10 mail.orionet.re" >> zones/pro-db.orionet.re
done
