version: '3'

services:
  bind:
    image: internetsystemsconsortium/bind9:9.16
    restart: unless-stopped
    volumes:
      - ./named.conf:/etc/bind/named.conf
      - bind_cache:/var/cache/bind
      - ./zones:/var/lib/bind
    networks:
      dns:
        ipv4_address: 192.168.43.2

  dnsdist:
    image: ghcr.io/matthieucoder/orion-dns-reverse-proxy:master
    restart: unless-stopped
    entrypoint: /dns-reverse-proxy
    command:
      - -default
      - 192.168.43.2:53
    expose:
      - '53/udp'
      - '53/tcp'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    networks:
      dns:
        ipv4_address: 192.168.43.3

volumes:
  bind_cache:

networks:
  dns:
    ipam:
      config:
        - subnet: 192.168.43.0/24
