services:
  smtp:
    build: .
    restart: always
    volumes:
      - ./transport:/etc/postfix/transport
      - ./main.cf:/etc/postfix/main.cf
      - ./relay:/etc/postfix/relay
      - ./certs:/certs
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    networks:
      smtp-relay:
        ipv4_address: 192.168.104.2
        ipv6_address: 2a02:c206:2201:3371:104::2

volumes:
  data-smtp-relay-auth:

networks:
  smtp-relay:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 192.168.104.0/24
        - subnet: 2a02:c206:2201:3371:104::/100
