version: '3'

services:
  looking-glass:
    image: gmazoyer/looking-glass:latest
    ports:
      - "127.0.0.1:5000:80"
    volumes:
      - ./config.php:/var/www/html/config.php
      - ./keys:/keys
    networks:
      looking-glass:
        ipv4_address: 192.168.32.2
networks:
  looking-glass:
    ipam:
      config:
        - subnet: 192.168.32.0/24
