version: '3'

services:
  sip-proxy:
    build: .
    volumes:
      - ./kamailio:/etc/kamailio
      - ./certs:/cert
    dns:
      - 192.168.31.2
    networks:
      sip-proxy:
        ipv4_address: 192.168.31.3
  unbound:
    image: mvance/unbound:latest
    volumes:
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf
    networks:
      sip-proxy:
        ipv4_address: 192.168.31.2
networks:
  sip-proxy:
    ipam:
      config:
        - subnet: 192.168.31.0/24
        
